// Generated by gencpp from file nmc_nlp_lite/nmcNLPRequest.msg
// DO NOT EDIT!


#ifndef NMC_NLP_LITE_MESSAGE_NMCNLPREQUEST_H
#define NMC_NLP_LITE_MESSAGE_NMCNLPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nmc_nlp_lite
{
template <class ContainerAllocator>
struct nmcNLPRequest_
{
  typedef nmcNLPRequest_<ContainerAllocator> Type;

  nmcNLPRequest_()
    : str()  {
    }
  nmcNLPRequest_(const ContainerAllocator& _alloc)
    : str(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _str_type;
  _str_type str;





  typedef boost::shared_ptr< ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator> const> ConstPtr;

}; // struct nmcNLPRequest_

typedef ::nmc_nlp_lite::nmcNLPRequest_<std::allocator<void> > nmcNLPRequest;

typedef boost::shared_ptr< ::nmc_nlp_lite::nmcNLPRequest > nmcNLPRequestPtr;
typedef boost::shared_ptr< ::nmc_nlp_lite::nmcNLPRequest const> nmcNLPRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator1> & lhs, const ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator2> & rhs)
{
  return lhs.str == rhs.str;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator1> & lhs, const ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nmc_nlp_lite

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "994972b6e03928b2476860ce6c4c8e17";
  }

  static const char* value(const ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x994972b6e03928b2ULL;
  static const uint64_t static_value2 = 0x476860ce6c4c8e17ULL;
};

template<class ContainerAllocator>
struct DataType< ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nmc_nlp_lite/nmcNLPRequest";
  }

  static const char* value(const ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string str\n"
;
  }

  static const char* value(const ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.str);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nmcNLPRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nmc_nlp_lite::nmcNLPRequest_<ContainerAllocator>& v)
  {
    s << indent << "str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.str);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NMC_NLP_LITE_MESSAGE_NMCNLPREQUEST_H
